name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches: [ "*" ]

jobs:
  validate-pull-request:
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    steps:
      - name: Validate PR Title
        uses: kontrolplane/pull-request-title-validator@v1.5.0
        with:
          types: "feat,fix,chore,docs,style,refactor,perf,test,build,ci"
          scopes: ".*"

  check-test:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    container:
      image: docker:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v4
      - run: apk add openjdk21
      - run: ./gradlew spotlessCheck
      - run: ./gradlew test

  build:
    runs-on: ubuntu-24.04
    needs: check-test
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.draft == false) ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main')

    steps:
      - uses: actions/checkout@v4

      - name: Login Dockerhub (only on main)
        if: github.ref == 'refs/heads/main'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.ref == 'refs/heads/main' && 'latest' || 'pr-build' }}
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:$IMAGE_TAG

      - name: Push to Dockerhub (only on main)
        if: github.ref == 'refs/heads/main'
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest

  deploy:
    runs-on: self-hosted
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest

      - name: Delete old container if existed
        run: docker rm -f ${{ secrets.DOCKER_CONTAINER_NAME }} || true

      - name: Run Docker container
        run: |
          docker run -d -p ${{ secrets.SERVER_PORT }}:${{ secrets.SERVER_PORT }} \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --name ${{ secrets.DOCKER_CONTAINER_NAME }} \
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest
